style: shfmt -s -w .
Signed-off-by: Jack Cherng <jfcherng@gmail.com>

diff --git a/general/init.d/mysqld b/general/init.d/mysqld
--- a/general/init.d/mysqld
+++ b/general/init.d/mysqld
@@ -62,20 +62,20 @@ lock_file_path="$lockdir/mysql"
 # Set some defaults
 mysqld_pid_file_path=
 if test -z "$basedir"; then
-        basedir=/usr/local/mysql
-        bindir=/usr/local/mysql/bin
-        if test -z "$datadir"; then
-                datadir=/data/mysql
-        fi
-        sbindir=/usr/local/mysql/bin
-        libexecdir=/usr/local/mysql/bin
+    basedir=/usr/local/mysql
+    bindir=/usr/local/mysql/bin
+    if test -z "$datadir"; then
+        datadir=/data/mysql
+    fi
+    sbindir=/usr/local/mysql/bin
+    libexecdir=/usr/local/mysql/bin
 else
-        bindir="$basedir/bin"
-        if test -z "$datadir"; then
-                datadir="$basedir/data"
-        fi
-        sbindir="$basedir/sbin"
-        libexecdir="$basedir/libexec"
+    bindir="$basedir/bin"
+    if test -z "$datadir"; then
+        datadir="$basedir/data"
+    fi
+    sbindir="$basedir/sbin"
+    libexecdir="$basedir/libexec"
 fi
 
 # datadir_set is used to determine if datadir was set (and so should be
@@ -87,14 +87,14 @@ datadir_set=
 #
 lsb_functions="/lib/lsb/init-functions"
 if test -f $lsb_functions; then
-        . $lsb_functions
+    . $lsb_functions
 else
-        log_success_msg() {
-                echo " SUCCESS! $@"
-        }
-        log_failure_msg() {
-                echo " ERROR! $@"
-        }
+    log_success_msg() {
+        echo " SUCCESS! $@"
+    }
+    log_failure_msg() {
+        echo " ERROR! $@"
+    }
 fi
 
 PATH="/sbin:/usr/sbin:/bin:/usr/bin:$basedir/bin"
@@ -110,112 +110,112 @@ other_args="$*" # uncommon, but needed when called from an RPM upgrade action
 # of the "spec" file author to give correct arguments only.
 
 case $(echo "testing\c"),$(echo -n testing) in
-*c*,-n*) echo_n= echo_c= ;;
-*c*,*) echo_n=-n echo_c= ;;
-*) echo_n= echo_c='\c' ;;
+    *c*,-n*) echo_n= echo_c= ;;
+    *c*,*) echo_n=-n echo_c= ;;
+    *) echo_n= echo_c='\c' ;;
 esac
 
 parse_server_arguments() {
-        for arg; do
-                case "$arg" in
-                --basedir=*)
-                        basedir=$(echo "$arg" | sed -e 's/^[^=]*=//')
-                        bindir="$basedir/bin"
-                        if test -z "$datadir_set"; then
-                                datadir="$basedir/data"
-                        fi
-                        sbindir="$basedir/sbin"
-                        libexecdir="$basedir/libexec"
-                        ;;
-                --datadir=*)
-                        datadir=$(echo "$arg" | sed -e 's/^[^=]*=//')
-                        datadir_set=1
-                        ;;
-                --pid-file=*) mysqld_pid_file_path=$(echo "$arg" | sed -e 's/^[^=]*=//') ;;
-                --service-startup-timeout=*) service_startup_timeout=$(echo "$arg" | sed -e 's/^[^=]*=//') ;;
-                esac
-        done
+    for arg; do
+        case "$arg" in
+            --basedir=*)
+                basedir=$(echo "$arg" | sed -e 's/^[^=]*=//')
+                bindir="$basedir/bin"
+                if test -z "$datadir_set"; then
+                    datadir="$basedir/data"
+                fi
+                sbindir="$basedir/sbin"
+                libexecdir="$basedir/libexec"
+                ;;
+            --datadir=*)
+                datadir=$(echo "$arg" | sed -e 's/^[^=]*=//')
+                datadir_set=1
+                ;;
+            --pid-file=*) mysqld_pid_file_path=$(echo "$arg" | sed -e 's/^[^=]*=//') ;;
+            --service-startup-timeout=*) service_startup_timeout=$(echo "$arg" | sed -e 's/^[^=]*=//') ;;
+        esac
+    done
 }
 
 wait_for_pid() {
-        verb="$1"          # created | removed
-        pid="$2"           # process ID of the program operating on the pid-file
-        pid_file_path="$3" # path to the PID file.
+    verb="$1"          # created | removed
+    pid="$2"           # process ID of the program operating on the pid-file
+    pid_file_path="$3" # path to the PID file.
 
-        i=0
-        avoid_race_condition="by checking again"
+    i=0
+    avoid_race_condition="by checking again"
 
-        while test $i -ne $service_startup_timeout; do
+    while test $i -ne $service_startup_timeout; do
 
-                case "$verb" in
-                'created')
-                        # wait for a PID-file to pop into existence.
-                        test -s "$pid_file_path" && i='' && break
-                        ;;
-                'removed')
-                        # wait for this PID-file to disappear
-                        test ! -s "$pid_file_path" && i='' && break
-                        ;;
-                *)
-                        echo "wait_for_pid () usage: wait_for_pid created|removed pid pid_file_path"
-                        exit 1
-                        ;;
-                esac
+        case "$verb" in
+            'created')
+                # wait for a PID-file to pop into existence.
+                test -s "$pid_file_path" && i='' && break
+                ;;
+            'removed')
+                # wait for this PID-file to disappear
+                test ! -s "$pid_file_path" && i='' && break
+                ;;
+            *)
+                echo "wait_for_pid () usage: wait_for_pid created|removed pid pid_file_path"
+                exit 1
+                ;;
+        esac
 
-                # if server isn't running, then pid-file will never be updated
-                if test -n "$pid"; then
-                        if kill -0 "$pid" 2>/dev/null; then
-                                : # the server still runs
-                        else
-                                # The server may have exited between the last pid-file check and now.
-                                if test -n "$avoid_race_condition"; then
-                                        avoid_race_condition=""
-                                        continue # Check again.
-                                fi
-
-                                # there's nothing that will affect the file.
-                                log_failure_msg "The server quit without updating PID file ($pid_file_path)."
-                                return 1 # not waiting any more.
-                        fi
+        # if server isn't running, then pid-file will never be updated
+        if test -n "$pid"; then
+            if kill -0 "$pid" 2>/dev/null; then
+                : # the server still runs
+            else
+                # The server may have exited between the last pid-file check and now.
+                if test -n "$avoid_race_condition"; then
+                    avoid_race_condition=""
+                    continue # Check again.
                 fi
 
-                echo $echo_n ".$echo_c"
-                i=$(expr $i + 1)
-                sleep 1
-
-        done
-
-        if test -z "$i"; then
-                log_success_msg
-                return 0
-        else
-                log_failure_msg
-                return 1
+                # there's nothing that will affect the file.
+                log_failure_msg "The server quit without updating PID file ($pid_file_path)."
+                return 1 # not waiting any more.
+            fi
         fi
+
+        echo $echo_n ".$echo_c"
+        i=$(expr $i + 1)
+        sleep 1
+
+    done
+
+    if test -z "$i"; then
+        log_success_msg
+        return 0
+    else
+        log_failure_msg
+        return 1
+    fi
 }
 
 # Get arguments from the my.cnf file,
 # the only group, which is read from now on is [mysqld]
 if test -x "$bindir/my_print_defaults"; then
-        print_defaults="$bindir/my_print_defaults"
+    print_defaults="$bindir/my_print_defaults"
 else
-        # Try to find basedir in /etc/my.cnf
-        conf=/etc/my.cnf
-        print_defaults=
-        if test -r $conf; then
-                subpat='^[^=]*basedir[^=]*=\(.*\)$'
-                dirs=$(sed -e "/$subpat/!d" -e 's//\1/' $conf)
-                for d in $dirs; do
-                        d=$(echo $d | sed -e 's/[  ]//g')
-                        if test -x "$d/bin/my_print_defaults"; then
-                                print_defaults="$d/bin/my_print_defaults"
-                                break
-                        fi
-                done
-        fi
+    # Try to find basedir in /etc/my.cnf
+    conf=/etc/my.cnf
+    print_defaults=
+    if test -r $conf; then
+        subpat='^[^=]*basedir[^=]*=\(.*\)$'
+        dirs=$(sed -e "/$subpat/!d" -e 's//\1/' $conf)
+        for d in $dirs; do
+            d=$(echo $d | sed -e 's/[  ]//g')
+            if test -x "$d/bin/my_print_defaults"; then
+                print_defaults="$d/bin/my_print_defaults"
+                break
+            fi
+        done
+    fi
 
-        # Hope it's in the PATH ... but I doubt it
-        test -z "$print_defaults" && print_defaults="my_print_defaults"
+    # Hope it's in the PATH ... but I doubt it
+    test -z "$print_defaults" && print_defaults="my_print_defaults"
 fi
 
 #
@@ -225,7 +225,7 @@ fi
 
 extra_args=""
 if test -r "$basedir/my.cnf"; then
-        extra_args="-e $basedir/my.cnf"
+    extra_args="-e $basedir/my.cnf"
 fi
 
 parse_server_arguments $($print_defaults $extra_args mysqld server mysql_server mysql.server)
@@ -234,16 +234,16 @@ parse_server_arguments $($print_defaults $extra_args mysqld server mysql_server 
 # Set pid file if not given
 #
 if test -z "$mysqld_pid_file_path"; then
-        mysqld_pid_file_path=$datadir/$(hostname).pid
+    mysqld_pid_file_path=$datadir/$(hostname).pid
 else
-        case "$mysqld_pid_file_path" in
+    case "$mysqld_pid_file_path" in
         /*) ;;
         *) mysqld_pid_file_path="$datadir/$mysqld_pid_file_path" ;;
-        esac
+    esac
 fi
 
 case "$mode" in
-'start')
+    'start')
         # Start daemon
 
         # Safeguard (relative paths, core dumps..)
@@ -251,109 +251,109 @@ case "$mode" in
 
         echo $echo_n "Starting MySQL"
         if test -x $bindir/mysqld_safe; then
-                # Give extra arguments to mysqld with the my.cnf file. This script
-                # may be overwritten at next upgrade.
-                $bindir/mysqld_safe --datadir="$datadir" --pid-file="$mysqld_pid_file_path" $other_args >/dev/null &
-                wait_for_pid created "$!" "$mysqld_pid_file_path"
-                return_value=$?
+            # Give extra arguments to mysqld with the my.cnf file. This script
+            # may be overwritten at next upgrade.
+            $bindir/mysqld_safe --datadir="$datadir" --pid-file="$mysqld_pid_file_path" $other_args >/dev/null &
+            wait_for_pid created "$!" "$mysqld_pid_file_path"
+            return_value=$?
 
-                # Make lock for RedHat / SuSE
-                if test -w "$lockdir"; then
-                        touch "$lock_file_path"
-                fi
+            # Make lock for RedHat / SuSE
+            if test -w "$lockdir"; then
+                touch "$lock_file_path"
+            fi
 
-                exit $return_value
+            exit $return_value
         else
-                log_failure_msg "Couldn't find MySQL server ($bindir/mysqld_safe)"
+            log_failure_msg "Couldn't find MySQL server ($bindir/mysqld_safe)"
         fi
         ;;
 
-'stop')
+    'stop')
         # Stop daemon. We use a signal here to avoid having to know the
         # root password.
 
         if test -s "$mysqld_pid_file_path"; then
-                # signal mysqld_safe that it needs to stop
-                touch "$mysqld_pid_file_path.shutdown"
+            # signal mysqld_safe that it needs to stop
+            touch "$mysqld_pid_file_path.shutdown"
 
-                mysqld_pid=$(cat "$mysqld_pid_file_path")
+            mysqld_pid=$(cat "$mysqld_pid_file_path")
 
-                if (kill -0 $mysqld_pid 2>/dev/null); then
-                        echo $echo_n "Shutting down MySQL"
-                        kill $mysqld_pid
-                        # mysqld should remove the pid file when it exits, so wait for it.
-                        wait_for_pid removed "$mysqld_pid" "$mysqld_pid_file_path"
-                        return_value=$?
-                else
-                        log_failure_msg "MySQL server process #$mysqld_pid is not running!"
-                        rm "$mysqld_pid_file_path"
-                fi
+            if (kill -0 $mysqld_pid 2>/dev/null); then
+                echo $echo_n "Shutting down MySQL"
+                kill $mysqld_pid
+                # mysqld should remove the pid file when it exits, so wait for it.
+                wait_for_pid removed "$mysqld_pid" "$mysqld_pid_file_path"
+                return_value=$?
+            else
+                log_failure_msg "MySQL server process #$mysqld_pid is not running!"
+                rm "$mysqld_pid_file_path"
+            fi
 
-                # Delete lock for RedHat / SuSE
-                if test -f "$lock_file_path"; then
-                        rm -f "$lock_file_path"
-                fi
-                exit $return_value
+            # Delete lock for RedHat / SuSE
+            if test -f "$lock_file_path"; then
+                rm -f "$lock_file_path"
+            fi
+            exit $return_value
         else
-                log_failure_msg "MySQL server PID file could not be found!"
+            log_failure_msg "MySQL server PID file could not be found!"
         fi
         ;;
 
-'restart')
+    'restart')
         # Stop the service and regardless of whether it was
         # running or not, start it again.
         if $0 stop $other_args; then
-                $0 start $other_args
+            $0 start $other_args
         else
-                log_failure_msg "Failed to stop running server, so refusing to try to start."
-                exit 1
+            log_failure_msg "Failed to stop running server, so refusing to try to start."
+            exit 1
         fi
         ;;
 
-'reload' | 'force-reload')
+    'reload' | 'force-reload')
         if test -s "$mysqld_pid_file_path"; then
-                read mysqld_pid <"$mysqld_pid_file_path"
-                kill -HUP $mysqld_pid && log_success_msg "Reloading service MySQL"
-                touch "$mysqld_pid_file_path"
+            read mysqld_pid <"$mysqld_pid_file_path"
+            kill -HUP $mysqld_pid && log_success_msg "Reloading service MySQL"
+            touch "$mysqld_pid_file_path"
         else
-                log_failure_msg "MySQL PID file could not be found!"
-                exit 1
+            log_failure_msg "MySQL PID file could not be found!"
+            exit 1
         fi
         ;;
-'status')
+    'status')
         # First, check to see if pid file exists
         if test -s "$mysqld_pid_file_path"; then
-                read mysqld_pid <"$mysqld_pid_file_path"
-                if kill -0 $mysqld_pid 2>/dev/null; then
-                        log_success_msg "MySQL running ($mysqld_pid)"
-                        exit 0
-                else
-                        log_failure_msg "MySQL is not running, but PID file exists"
-                        exit 1
-                fi
+            read mysqld_pid <"$mysqld_pid_file_path"
+            if kill -0 $mysqld_pid 2>/dev/null; then
+                log_success_msg "MySQL running ($mysqld_pid)"
+                exit 0
+            else
+                log_failure_msg "MySQL is not running, but PID file exists"
+                exit 1
+            fi
         else
-                # Try to find appropriate mysqld process
-                mysqld_pid=$(pidof $libexecdir/mysqld)
+            # Try to find appropriate mysqld process
+            mysqld_pid=$(pidof $libexecdir/mysqld)
 
-                # test if multiple pids exist
-                pid_count=$(echo $mysqld_pid | wc -w)
-                if test $pid_count -gt 1; then
-                        log_failure_msg "Multiple MySQL running but PID file could not be found ($mysqld_pid)"
-                        exit 5
-                elif test -z $mysqld_pid; then
-                        if test -f "$lock_file_path"; then
-                                log_failure_msg "MySQL is not running, but lock file ($lock_file_path) exists"
-                                exit 2
-                        fi
-                        log_failure_msg "MySQL is not running"
-                        exit 3
-                else
-                        log_failure_msg "MySQL is running but PID file could not be found"
-                        exit 4
+            # test if multiple pids exist
+            pid_count=$(echo $mysqld_pid | wc -w)
+            if test $pid_count -gt 1; then
+                log_failure_msg "Multiple MySQL running but PID file could not be found ($mysqld_pid)"
+                exit 5
+            elif test -z $mysqld_pid; then
+                if test -f "$lock_file_path"; then
+                    log_failure_msg "MySQL is not running, but lock file ($lock_file_path) exists"
+                    exit 2
                 fi
+                log_failure_msg "MySQL is not running"
+                exit 3
+            else
+                log_failure_msg "MySQL is running but PID file could not be found"
+                exit 4
+            fi
         fi
         ;;
-*)
+    *)
         # usage
         basename=$(basename "$0")
         echo "Usage: $basename  {start|stop|restart|reload|force-reload|status}  [ MySQL server options ]"
